### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by KoldBrewEd** [awslabs/aws-cognito-angular2-quickstart#16]
I'm getting the following error, any idea what might be causing it?

```
> npm start

> aws-cognito-angular2-quickstart@1.0.0 start /Users/xxxxx/Scripts/Angular/aws-cognito-angular2-quickstart
> ng server


It seems like you're using the newest version of the Angular CLI that uses webpack.
This version does not require an angular-cli-build file, but your project has one.
It will be ignored.

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
The "defaults.prefix" and "defaults.sourceDir" properties of angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of angular-cli.
The "defaults.prefix" and "defaults.sourceDir" properties of angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of angular-cli.
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.getWebpackCommonConfig (/Users/xxxxxx/Scripts/Angular/aws-cognito-angular2-quickstart/node_modules/angular-cli/models/webpack-build-common.js:20:25)
    at new NgCliWebpackConfig (/Users/xxxxxx/Scripts/Angular/aws-cognito-angular2-quickstart/node_modules/angular-cli/models/webpack-config.js:15:29)
    at Class.run (/Users/xxxxxx/Scripts/Angular/aws-cognito-angular2-quickstart/node_modules/angular-cli/tasks/serve-webpack.js:19:22)
    at /Users/xxxxxx/Scripts/Angular/aws-cognito-angular2-quickstart/node_modules/angular-cli/commands/serve.js:85:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! aws-cognito-angular2-quickstart@1.0.0 start: `ng server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-cognito-angular2-quickstart@1.0.0 start script 'ng server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-cognito-angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-cognito-angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-cognito-angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxxx/Scripts/Angular/aws-cognito-angular2-quickstart/npm-debug.log
```

**Comment by gersonadr** [comment]
Got this error, then ran "npm upgrade" and it worked.

npm v3.5.2 and node v4.2.6

**Comment by KoldBrewEd** [comment]
That did the trick. Thanks!
