### ISSUE TITLE
Unexpected token {  When npm start

### ISSUE THREAD

**Issue by sarunl** [awslabs/aws-cognito-angular2-quickstart#47]
Could you please help me with this?

Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/@ngtools/webpack/src/index.js:5:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Class.module.exports.includedCommands (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/addon/index.js:21:16)
    at /Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/angular-cli/lib/models/project.js:426:30)
    at module.exports (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/Ran/Programming/Asiawarehouse/AWSCognitoAngularTest/aws-cognito-angular2-quickstart/node_modules/rsvp/dist/rsvp.js:2373:5)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

**Comment by sarunl** [comment]
Fixed by upgrading node to version 7
