### ISSUE TITLE
npm start emits broccoli error

### ISSUE THREAD

**Issue by taji** [awslabs/aws-cognito-angular2-quickstart#7]
I've installed all of the dependencies and followed the instructions on setting up cognito.  Everything is configured but I'm getting the error below on npm start.  I googled the error and found this issue on github:

[https://github.com/angular/angular-cli/issues/873](https://github.com/angular/angular-cli/issues/873)

Could it be a version problem with angular-cli?   They are right in the middle of migrating from broccoli to webpack, but I'm not sure I should be upgrading/downgrading.  Here are the versions I'm running:

angular-cli: 1.0.0-beta.10
node: 4.4.5
aws-cli/1.10.59 Python/2.7.6 Linux/4.2.0-c9 botocore/1.4.49
$ bower --version
1.7.9

Here's the error:

```
taji:~/workspace (master) $ npm start

> aws-cognito-angular2-quickstart@1.0.0 start /home/ubuntu/workspace
> ng server

Livereload server on http://localhost:49152
Serving on http://localhost:8080/
File: input (10)
The Broccoli Plugin: [LESSPlugin] failed with:
undefined

The broccoli plugin was instantiated at: 
    at LESSPlugin.Plugin (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at LESSPlugin.CachingWriter [as constructor] (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at new LESSPlugin (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular-broccoli-less.js:21:12)
    at Object.Plugin.build.compile.exports.makeBroccoliTree (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular-broccoli-less.js:52:12)
    at Angular2App._buildTree (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular2-app.js:133:27)
    at new Angular2App (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/home/ubuntu/workspace/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)



```

**Comment by taji** [comment]
Following up.  As the error states, it's a less compilation issue, but broccoli is suppressing the actual error details.  I added the diagnostics that db6edr recommended here:

[https://github.com/angular/angular-cli/issues/873](https://github.com/angular/angular-cli/issues/873)

There are about 20 messages indicating undefined less variables in bootstrap-social.less and bootstrap.  Here are two of them:

```
error: { [Error: variable @line-height-computed is undefined]
  type: 'Name',
  filename: 'input',
  index: 187,
  line: 10,
  callLine: NaN,
  callExtract: undefined,
  column: 18,
  extract: 
   [ '',
     '@bs-height-base: (@line-height-computed + @padding-base-vertical * 2);',
     '@bs-height-lg:   (floor(@font-size-large * @line-height-base) + @padding-large-vertical * 2);' ],
  message: 'variable @line-height-computed is undefined',
  stack: undefined }
error: { [Error: variable @alert-padding is undefined]
  type: 'Name',
  filename: 'input',
  index: 134,
  line: 10,
  callLine: NaN,
  callExtract: undefined,
  column: 11,
  extract: 
   [ '.alert {',
     '  padding: @alert-padding;',
     '  margin-bottom: @line-height-computed;' ],
  message: 'variable @alert-padding is undefined',
  stack: undefined }
```

I've tried the various workarounds from the github issue thread, but no luck so far.

On another note, any thoughts about upgrading the project to angular 2 rc6?  According to the documentation, there "shouldn't" be any more breaking changes.

**Comment by taji** [comment]
Am I the only one running into this problem?  Any help is most appreciated.

**Comment by vbudilov** [comment]
Hi @taji , 

Let me try to build this app from scratch and let you know. I haven't seen this error before. Will get back to you shortly. 

Thanks,
Vladimir Budilov

**Comment by vbudilov** [comment]
Hi @taji , 

I'm not seeing the error when starting from scratch. Not sure what could be causing this on your end. 

I'm also working on upgrading the codebase to use RC6. 

Thanks,
Vladimir Budilov

**Comment by taji** [comment]
Good to know, I'll try it again and see.  Can you verify the version of angular cli you are using?

**Comment by vbudilov** [comment]
Here you go: 

angular-cli: 1.0.0-beta.10
node: 4.2.6
os: linux x64

bower -v
1.7.9

**Comment by vbudilov** [comment]
@taji -- are you still experiencing this issue?

**Comment by taji** [comment]
Retrying now. Should know in a few.

**Comment by taji** [comment]
First, thanks for following up. :-)

Okay, started from scratch in a clean cloud9 environment.   I've written an install script for the global dependencies as so:

```
cd ~

sudo apt-get update
sudo apt-get install python2.7-dev
git clone https://github.com/facebook/watchman.git
cd watchman
./autogen.sh
./configure
make
sudo make install

npm install -g angular-cli@1.0.0-beta.10 bower

sudo pip install awscli

cd ~/workspace

npm install
bower install

```

This worked, but I had to specify the exact version of angular-cli in the package.json ( "angular-cli": "1.0.0-beta.10"). 

Also, the "install bower" command emitted the following query (I selected option 3):

```
Unable to find a suitable version for font-awesome, please choose one by typing one of the numbers below:
    1) font-awesome#~4.2 which resolved to 4.2.0 and is required by bootstrap-social#4.8.0
    2) font-awesome#^4.2.0 which resolved to 4.6.3 and is required by aws-cognito-angular2-quickstart
    3) font-awesome#~4.6.3 which resolved to 4.6.3 and is required by startbootstrap-sb-admin-2#20f6ac3081

Prefix the choice with ! to persist it to bower.json

? Answer 3
```

Here are the versions of the installed global dependencies:
node: v4.2.6
npm: 3.10.7
aws-cli/1.10.64 Python/2.7.6 Linux/4.2.0-c9 botocore/1.4.54
angular-cli: 1.0.0-beta.10
node: 4.2.6
os: linux x64
bower: 1.7.9

Unfortunately, I'm hitting the exact same less compilation error:

```
 npm start

> aws-cognito-angular2-quickstart@1.0.0 start /home/ubuntu/workspace
> ng server

Livereload server on http://localhost:49152
Serving on http://localhost:8080/
File: input (10)
The Broccoli Plugin: [LESSPlugin] failed with:
undefined

The broccoli plugin was instantiated at: 
    at LESSPlugin.Plugin (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at LESSPlugin.CachingWriter [as constructor] (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at new LESSPlugin (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular-broccoli-less.js:21:12)
    at Object.Plugin.build.compile.exports.makeBroccoliTree (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular-broccoli-less.js:52:12)
    at Angular2App._buildTree (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular2-app.js:133:27)
    at new Angular2App (/home/ubuntu/workspace/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/home/ubuntu/workspace/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/ubuntu/workspace/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/ubuntu/workspace/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

```

Here's my fork of your environment -- with my install script and the update to the package.json:

[https://github.com/taji/aws-cognito-angular2-quickstart](https://github.com/taji/aws-cognito-angular2-quickstart)

Maybe you could try installing to C9 and see if it works? Or I'm open to any other suggestions.

**Comment by taji** [comment]
Also, I've made a public workspace for this project here:

[https://ide.c9.io/taji/aws-cognito-angular2-quickstart5](https://ide.c9.io/taji/aws-cognito-angular2-quickstart5)

**Comment by vbudilov** [comment]
Hi @taji , unfortunately I won't be able to debug your code, but are you able to clone this repo and run npm install without making any modifications to the package file? Does that work?

**Comment by taji** [comment]
No worries, you can close this.  I'll resume work on this once your updates for Angular 2 final are completed.  Thanks for the help. :)

**Comment by vbudilov** [comment]
Closing :)
